import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Модули SOM',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'modules' }],
    },
    {
      type: 'category',
      label: 'Несущие платы',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'carrier-boards' }],
    },
    {
      type: 'category',
      label: 'Руководства (SW)',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'software-guides' }],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      link: { type: 'generated-index' },
      items: [{ type: 'autogenerated', dirName: 'troubleshooting' }],
    },
  ],
};

export default sidebars;
